###GET ALL Todolist
GET http://127.0.0.1:5000/v1 HTTP/1.1

###GET Single Todolist
GET http://127.0.0.1:5000/v1/1 HTTP/1.1

###ADD New TodoList
POST http://127.0.0.1:5000/v1 HTTP/1.1
Content-Type: application/json

{
    "title":"task3",
    "description":"this is task 3"
}

###DELETE Todolist
DELETE  http://127.0.0.1:5000/v1/3 HTTP/1.1

###UPDATE TodoList
PUT http://127.0.0.1:5000/v1/2 HTTP/1.1
Content-Type: application/json

{
    "title":"updated",
    "description":"updated"
}

###GET ALL Todolist
GET http://localhost:5000/time HTTP/1.1